### PR TITLE
"Refactor connection code to use pg8000 and return a cursor for JSON converter"

### PR DESCRIPTION
**Pull request by jambent**

### CODE REVIEW

**Comment by emanyika** [comment]
hi, the get_conn function should just return the connection so that I can access the db using my function. the get_conn function doesn't need to query the db

**Review by emanyika — COMMENTED** [review]
hi, i think the get_conn function should simply be connecting to the database. so something like this: import pg8000

def get_conn(user, password, host, database):
    try:
        conn = pg8000.connect(user=user, password=password, host=host, database=database)
        cursor = conn.cursor()
        return conn, cursor

**Comment by jambent** [comment]
It's only querying the DB to demonstrate that the connection is working.  It should absolutely be replaced by the actual query functionality we're going to use for real.

**Review by emanyika — APPROVED** [review]

**Comment by emanyika** [comment]
oh okay, i didnt read the code properly! my bad!

**Pull request merged**
