### PR TITLE
"Upload DB connection code to ingestion lambda"

### PR DESCRIPTION
**Pull request by jambent**
Requires additional files at the top directory level of the repo:
secret_oltp.json
secret_olap.json
, containing the oltp login details and olap login details, respectively.

Uses a temporary boto3 layer and credentials stored in SecretsManager, that can be removed once the GitHub secrets solution has been incorporated.

### CODE REVIEW

**Comment by jambent** [comment]
Ignore the comment about removing boto from the layers:  it's required for the incorporation of the Secrets Manager functions.

**Review by samule-i — CHANGES_REQUESTED** [review]
Can we delete
  response.json,
  aws_assets/pg8000_layer.zip:Zone.Identifier

Remove comments that aren't needed
Fix the conflict from provider.tf (Just delete that line about totesys, it's not useful)

**Review by RonanTC — CHANGES_REQUESTED** [review]
We probably shouldn't include the tfstate files?

Real credentials on line 6-9 of src/ingestion.py. Should probably squash this branch on merge after this is changed.

I got some missing resource errors trying to replicate this locally e.g.:
`Error: Unable to load "./../aws_assets/boto3_layer.zip": open ./../aws_assets/boto3_layer.zip: no such file or directory`

Should there be a data declaration for this file?

**Comment by jambent** [comment]
Looks like the last commit I did last night failed, hence visible DB credentials, missing boto3 layer, etc.

I'll roll all of this into branch add_secretsmanager_to_ingestion instead.

**Pull request closed without merging**
